In [1]:
%config Completer.use_jedi = False
# 자동완성 위한 설정

In [3]:
import numpy as np

v1=np.array([1,2,3,4])

for i in range(len(v1)):
    print(v1[i])

1
2
3
4


In [4]:
v1 = np.arange(5)
print(v1)

[0 1 2 3 4]


In [5]:
v2 = np.arange(1,10,2, dtype=int)
v3 = np.arange(3.5, 10.5, 2, dtype=float)
print("v2:", v2)
print("v3:", v3)

v2: [1 3 5 7 9]
v3: [3.5 5.5 7.5 9.5]


In [6]:
n=6
v4 = np.arange(1,10,2)**2
v5 = np.arange(1,10,2)**3
v6 = np.arange(2,13,2,dtype=int)**n
print(v4)
print(v5)
print(v6)

[ 1  9 25 49 81]
[  1  27 125 343 729]
[     64    4096   46656  262144 1000000 2985984]


In [7]:
v1 = np.arange(1,5).reshape(2,2)
print(v1)

[[1 2]
 [3 4]]


In [8]:
print(np.add(v1,v1))

[[2 4]
 [6 8]]


In [10]:
print(np.subtract(v1,v1))

[[0 0]
 [0 0]]


In [11]:
print(np.multiply(v1,v1))

[[ 1  4]
 [ 9 16]]


In [12]:
print(np.dot(v1,v1))

[[ 7 10]
 [15 22]]


In [15]:
v1=np.arange(12)
print(v1)
v2=v1.reshape(2,3,2, order="F")
v3=v1.reshape(2,3,2)
print(v2)
print(v3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [16]:
print(v2.shape)

(2, 3, 2)


In [17]:
v3=np.arange(3.5,10.5,2, dtype=float)
print(v3)
v4=np.arange(1,5).reshape(2,2)
print(v4)

[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]


In [18]:
print(np.amax(v3))
print(np.amax(v4))
print(np.amin(v3))
print(np.amin(v4))
print(np.sum(v3))
print(np.sum(v4))
print(v3.sum())
print(v4.sum())
print(v4.diagonal())

9.5
4
3.5
1
26.0
10
26.0
10
[1 4]
